#AutenticaBundle:
#    resource: "@AutenticaBundle/Controller/"
#    type:     annotation
#    prefix:   /

ProcuraBundle:
    resource: "@ProcuraBundle/Controller/"
    type:     annotation
    prefix:   /

ConfiguraObraBundle:
    resource: "@ConfiguraObraBundle/Controller/"
    type:     annotation
    prefix:   /

ContactoBundle:
    resource: "@ContactoBundle/Controller/"
    type:     annotation
    prefix:   /

#Inicio:
#    pattern: /sitio/{pagina}
#    defaults: { _controller:ContactoBundle:Sitio:estatica #}

#login:
#    pattern: /login
#    defaults: { _controller:AutenticaBundle:Security:login }

#login_check:
#    pattern: /login_check

#logout:
#    pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
